# Generated by Django 2.2 on 2021-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Processing'), (4, 'Shipping'), (5, 'Delivered')], default=1),
        ),
    ]
