# Generated by Django 2.2 on 2021-02-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210221_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Proposed'), (2, 'Pending'), (3, 'Cancelled'), (4, 'Confirmed'), (5, 'Processing'), (6, 'Shipping'), (7, 'Delivered')], default=1),
        ),
    ]
