# Generated by Django 2.2 on 2021-02-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210224_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Proposed', 'Proposed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='Proposed', max_length=20),
        ),
    ]
