# Generated by Django 2.2 on 2021-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(default='Unpaid', max_length=20),
        ),
    ]
