# Generated by Django 2.2 on 2021-03-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210303_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='billing',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='check_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='check_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='partial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='payment_type',
            field=models.CharField(choices=[('Full', 'Full'), ('Partial', 'Partial')], default='Full', max_length=20),
        ),
        migrations.AddField(
            model_name='merchant',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='merchant',
            name='agreement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='merchant',
            name='md_contact_details',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='tin_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
