# Generated by Django 2.2 on 2021-03-09 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20210305_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing',
            old_name='partial_amount',
            new_name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='check_no',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='received',
        ),
        migrations.AddField(
            model_name='billing',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='merchantpermission',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantpermission',
            name='user_type',
            field=models.CharField(choices=[('procurement', 'Procurement'), ('store manager', 'Store Manager'), ('accounts', 'Accounts')], default='procurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='billing',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='billing', serialize=False, to='api.Order'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('check_no', models.CharField(blank=True, max_length=100, null=True)),
                ('check_date', models.DateField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('Full', 'Full'), ('Partial', 'Partial')], default='Full', max_length=20)),
                ('partial_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='')),
                ('received', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.Billing')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
